/*
 * mangle_matcher.hpp
 *
 *  Created on: 08.10.2015
 *      Author: Klemens
 */

#ifndef INCLUDE_BOOST_DLL_DETAIL_POSIX_SIGNATURE_MATCHER_HPP_
#define INCLUDE_BOOST_DLL_DETAIL_POSIX_SIGNATURE_MATCHER_HPP_





#endif /* INCLUDE_BOOST_DLL_DETAIL_POSIX_SIGNATURE_MATCHER_HPP_ */
